= {lab_name}

Welcome to our interactive lab on using Configuration as code to configure the Ansible Automation Platrom.

Configuration as Code(CasC) is the way to maintain all your infrastructure.

This lab will provide code to demonstrate how to use CasC to maintain all aspects of AAP. The provided code will be a starting point, and will guide the user through how to utilize the code, and make it their own. This lab will cover configuring controller, private automation hub, execution environments, as well as the creation of workflows without the GUI as an example to follow along. These principles will help to prevent drift in configuration, allow changes to require approval before implementation, and help to maintain both a development and prod deployment.

It is Recomended to be familiar with the Automation Controller and Ansible as this lab assumes you are familier with using those products.

If you have not used the Automation controller before, a recomended place to start is this instruct lab, if you have not done so before: https://developers.redhat.com/content-gateway/link/3884764[Introduction to automation controller] 

== Lab structure

Wether you are writing a lab

* First, We will setup the basics for configuring the Automation Platform.

* Next we will configure the Hub to load in more content.

* Next we will Create some credentials, inventories, and job templates and everything that is needed to create them.

* We will then build an execution environment to be used on the platform.

* Finally for extra credit, a workflow can be created from scratch.

=== Lab Access

The terminal window to your right is *already* logged into the lab environment.
