== 👋 Configuring the Automation controller

In this section, you will only be given a summary of the objects you
need to create along with some screenshots of a controller that is
configured with the completed code. You will also be provided the
variables sections from the readme’s for each of the required roles to
help you complete this task.

== Task 1 - Configure settings

Create a file `group_vars/all/settings.yml` and copy all this into the
file.

[source,yaml]
----
---
controller_settings:
  settings:
    GALAXY_IGNORE_CERTS: true
...
----

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/settings/README.md[settings
role]

== Task 2 - Configure Execution Environments

Create a file `group_vars/all/execution_environments.yml` and add the
required information to the list `controller_execution_environments`
to include a new EE (that we will show how to create with code in the next module) called `config_as_code` with image path `{{ aap_hostname }}/config_as_code` that is pull `always` and uses the credential `cr_ah`.

[source,yaml]
----
---
controller_execution_environments:
  - name: "supported"
    image: "{{ aap_hostname }}/ee-supported-rhel8"
    pull: always
    credential: cr_ah

  - name: "minimal"
    image: "{{ aap_hostname }}/ee-minimal-rhel8"
    pull: always
    credential: cr_ah

...

----

Note: While you have not created this EE yet it, we have already added a version to hub so this won't fail.

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/execution_environments/README.md[execution
environments role]

== Task 3 - Create credential types

Create a file `group_vars/all/credential_types.yml` where we will
create a list called `controller_credential_types` that has 5
variables per item which are:

* `name` this is required and will be what the credential type will be
called
* `description` this is the description of the credential type
* `kind` The type of credential type being added. Note that only cloud
and net can be used for creating credential types.
* `inputs` Enter inputs using either JSON or YAML syntax. Refer to the
Ansible controller documentation for example syntax. These will be the
fields in the GUI that prompt the user for input.
* `injectors` Enter injectors using either JSON or YAML syntax. Refer
to the Ansible controller documentation for example syntax. These are
the variables that will then be useable in a job.

which the role will loop over and for each item in this list it will
create custom credential types for use in the controller.

[source,yaml]
----
---
controller_credential_types:
  - name: automation_hub
    description: automation hub
    kind: cloud
    inputs:
      fields:
        - id: verify_ssl
          type: boolean
          label: Verify SSL
        - id: hostname
          type: string
          label: Hostname
        - id: username
          type: string
          label: Username
        - id: password
          type: string
          label: Password
          secret: true
        - id: token
          type: string
          label: Token
          secret: true
      required:
        - hostname
    injectors:
      env:
        AAP_PASSWORD: !unsafe "{{ password }}"
        AAP_USERNAME: !unsafe "{{ username }}"
        AAP_HOSTNAME: !unsafe # Insert appropriate variable from above here
        AAP_TOKEN: !unsafe # Insert appropriate variable from above here
        AAP_VALIDATE_CERTS: !unsafe # Insert appropriate variable from above here
      extra_vars:
        aap_password: !unsafe "{{ password }}"
        aap_username: !unsafe "{{ username }}"
        aap_hostname: !unsafe # Insert appropriate variable from above here
        aap_token: !unsafe # Insert appropriate variable from above here
        aap_validate_certs: !unsafe # Insert appropriate variable from above here

  - name: ssh_priv_file
    kind: cloud
    description: creates temp ssh priv key to use (cannot have passphrase)
    inputs:
      fields:
        - id: priv_key
          type: string
          label: Certificate
          format: ssh_private_key
          multiline: true
          secret: true
    injectors:
      env:
        MY_CERT_FILE_PATH: !unsafe '{{ tower.filename.cert_file }}'
      file:
        template.cert_file: !unsafe '{{ priv_key }}'
...
----

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/credential_types/README.md[credential
types role]

== Task 4 - Create organizations

Create a file `group_vars/all/organizations.yml` and add the required
information to the list `controller_organizations` to configure the UI
to look like the screenshot

[source,yaml]
----
---
controller_organizations:
...
----

NOTE: Insert Screenshot with the execution environment supported and galaxy credentials

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/organizations/README.md[organizations
role]

== Task 5 - Create credentials

Create a file `group_vars/all/credentials.yml` and add the required
information to the list `controller_credentials` to configure the UI
to look like the screenshot. Make it to look like the screenshot, but
make sure to use parameters for the values. DO NOT PASTE YOUR CLEARTEST
CREDENTIALS!

[source,yaml]
----
---
controller_credentials:
  - name: aap_admin
    credential_type: Red Hat Ansible Automation Platform
    organization: config_as_code
    description: aap admin account
    inputs:
      host: "{{ controller_hostname }}"
      username: "{{ controller_username }}"
      password: "{{ controller_password }}"
      verify_ssl: false

  - name: ah_token_user
    credential_type: automation_hub
    organization: config_as_code
    description: automation hub api account
    inputs:
      hostname: "{{ aap_hostname }}"
      username: "{{ ah_token_username }}"
      token: "{{ ah_token }}"
      verify_ssl: false

  - name: ah_certified
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: "https://{{ aap_hostname }}/api/galaxy/content/rh-certified/"
      token: "{{ ah_token }}"

  - name: ah_published
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: "https://{{ aap_hostname }}/api/galaxy/content/published/"
      token: "{{ ah_token }}"

  - name: community-infra-repo
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: config_as_code
    inputs:
      url: "https://{{ aap_hostname }}/api/galaxy/content/community-infra-repo/"
      token: "{{ ah_token }}"

  - name: cr_ah
    credential_type: Container Registry
    organization: config_as_code
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ ah_username }}"
      password: "{{ ah_password }}"
      verify_ssl: false

  - name: root
    credential_type: Machine
    organization: config_as_code
    description: local password
    inputs:
      username: student
      password: "{{ machine_pass }}"

  - name: github
    credential_type: Source Control
    organization: config_as_code
    description: git
    inputs:
      username: "{{ student_account }}"
      password: "{{ machine_pass }}"

  - name: vault
    credential_type: Vault
    organization: config_as_code
    description: vault password
    inputs:
      vault_password: "{{ vault_pass }}"
...
----

NOTE: Insert Screenshot with the ah_admin_user_pass credential


Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/infra.aap_configuration/blob/devel/roles/controller_credentials/README.md[credentials
role]

== Task 6 - Create projects

Create a file `group_vars/all/projects.yml` and add the required
information to the list `controller_projects` to configure the UI to
look like the screenshot.

==== What git project are we pointing at

[source,yaml]
----
---
controller_configuration_projects_async_delay: 5
controller_projects:

...
----

NOTE: Insert Screenshot with the project

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/projects/README.md[projects
role]

== Task 7 - Create inventories

Create a file `group_vars/all/inventories.yml` and add the required
information to the list `controller_inventories` to configure the UI
to look like the screenshot

[source,yaml]
----
---
controller_inventories:

...
----

NOTE: Insert Screenshot with the inventories

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/inventories/README.md[inventories
role]

== Task 8 - Create inventory sources

Create a file `group_vars/all/inventory_sources.yml` and add the
required information to the list `controller_inventory_sources` to
configure the UI to look like the screenshot *NOTE the inventory file
name should be just inventory.yml*

[source,yaml]
----
---
controller_inventory_sources:

...
----

NOTE: Insert Screenshot with the inventory source

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/inventory_sources/README.md[inventory
sources role]

== Task 9 - Create job_templates

Create a file `group_vars/all/job_templates.yml` and add the required
information to the list `controller_templates` to configure the UI to
look like the screenshot

Pay attention to the credentials attached to each job template.

[source,yaml]
----
---
controller_templates:

...
----

NOTE: Insert Screenshot with the job template

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/controller_configuration/blob/devel/roles/job_templates/README.md[job
templates role]

== Task 10 - Update the Plabook
== Update the playbook to get the hub token for the configuration


The next step is to create a playbook/file `playbooks/aap_config.yml` that will call the aap_configuration dispatch role which will apply all provided configurations in the order that they need to be created.

```yaml
---
- name: Playbook to configure ansible controller post installation
  hosts: all
  gather_facts: false
  vars_files:
    - ../vault.yml
  connection: local
  tasks:
    - name: Authenticate and get an API token from Automation Hub
      ansible.hub.ah_token:
        ah_host: "{{ aap_hostname }}"
        ah_username: "{{ aap_username  }}"
        ah_password: "{{ aap_password }}"
        ah_path_prefix: 'galaxy'  # this is for private automation hub
        ah_verify_ssl: false

    - name: Fixing format
      ansible.builtin.set_fact:
        ah_token: "{{ ah_token['token'] }}"

    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
...


== Task 10 - Run the playbook

Run aap_config playbook.

[source,console]
----
ansible-playbook playbooks/aap_config.yml -i inventory.yml -l execution
----

if you run into problems, look back at the section that failed, and check the documentation for that role that was linked. If the output was hidden, look for 'Secure logging variables'

If you run into an error that says "Failed to get token: HTTP Error 401: Unauthorized" while other tasks pass, please rerun the playbook, this is a known issue.

== Task 11 - See the Results

After the playbook is complete you should be able to navigate to the
controller and see all the changes.

== ✅ Next Challenge

Press the `Next` button below to go to the next challenge once you’ve
completed the tasks.
