== Creating an Execution Environment

In this section we will show you step by step how to build an Execution
Environment (EE) from code. You will also be publishing this EE to your
own private automation hub which you will use in the rest of the tasks.

== Task 1 - Create our EE Definition

Create a file `+group_vars/all/ah_ee_list.yml+` where we will create a
list called `+ee_list+` that has 4 variables per item which are:

* `+name+` this is required and will be what the EE image will be called
* `+bindep+` this is any system packages that would be needed
* `+python+` these are any python modules that need to be added through
pip (excluding ansible)
* `+collections+` any collections that you would like to be built into
your EE image

// TODO - I'm not sure the above is actually correct is it? I'm also not 100% clear what we want them to do here. Just copy the below?

which the role will loop over and for each item in this list it will
create and publish an EE using the provided variables.

[source,yaml,role=execute]
----
---
ee_list:
  - name: "config_as_code"
    pull: always
    dependencies:
      galaxy:
        collections:
          - name: infra.aap_configuration
            version: 3.1.0
          - name: infra.ee_utilities
            version: 4.0.0
          - name: ansible.platform
            version: 2.5.20250213
          - name: ansible.hub
            version: 1.0.0
          - name: ansible.controller
            version: 4.6.8
          - name: containers.podman
            version: 1.16.3
          - name: community.general
            version: 10.4.0
    build_files:
      - src: /home/lab-user/casc_lab/ansible.cfg
        dest: configs
    build_steps:
      prepend_galaxy:
        - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
ee_build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-vvvv'

prepend_galaxy:
  - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

ee_base_image: "{{ aap_hostname }}/ee-minimal-rhel8:latest"
ee_image_push: true
ee_prune_images: false
ee_create_ansible_config: false
ee_pull_collections_from_hub: false
ee_create_controller_def: true
...
----

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/infra.aap_configuration/blob/devel/roles/controller_settings[settings role]

== Task 2 - Double check your Execution Environments

Check the file `group_vars/all/execution_environments.yml` and add make sure the `config_as_code` execution environment is there, you can also look in the gui. 
It should be listed with image path `{{ aap_hostname }}/config_as_code` that is pull `always` and uses the credential `cr_ah`.

// TODO - Is it worth just providing the end result here as they are just checking. i.e. we just give them the correct object.

[source,yaml,role=execute]
----
---
controller_execution_environments:
  <...>
  - name: "config_as_code"
    image: "{{ aap_hostname }}/config_as_code"
    pull: always
    credential: cr_ah
...
----

Further documentation for those who are interested to learn more see:

* https://github.com/redhat-cop/infra.aap_configuration/blob/devel/roles/controller_execution_environments[execution environments role]


== Task 3 - Create the the Playbook
=== Create a playbook to build an EE

The next step is to create a playbook/file `playbooks/build_ee.yml` which will run the ee_builder role to create the EE and push it to your Private Automation Hub.

[source,yaml,role=execute]
----
- name: Playbook to configure execution environments
  hosts: execution
  gather_facts: false
  connection: local
  vars_files:
    - "../vault.yml"
  tasks:
    - name: Include ee_builder role
      ansible.builtin.include_role:
        name: infra.ee_utilities.ee_builder
...
----


== Task 4 - Run the Playbook

Run the playbook pointing to the recently created inventory file and
limit the run to just execution to build your new custom EE and publish it
to Private Automation Hub.

[source,console]
----
ansible-playbook -i inventory.yml -l execution playbooks/build_ee.yml
----

Further documentation for those who are interested to learn more see:

* https://docs.ansible.com/ansible/latest/cli/ansible-playbook.html#ansible-playbook[more
on ansible-playbook]

== Task 5 - See the Results

Navigate to the AAP login with the provided passwords

In each applications respective Execution Environment section on the
left side you should find the `+config_as_code+` Execution Environment.


== ✅ Next Challenge

Press the `Next` button below to go to the next challenge once you’ve
completed the tasks.
